parameters:
    wealthbot_docusign.connection:
        username:       14d3fac4-ea15-46e9-95f8-96c84c3c8b51
        password:       pass4wealthbot
        integratorKey:  ROOW-10ed1300-2a9d-4169-b30c-f2849d8be519
        brand_id:       %docusign_brand_id%
        #account_id:     350278
    wealthbot_docusign.templates:
        personal_account:               EA155B06-5CAD-4E27-997E-385A5E4F8349
        ira_account:                    0DE8E1BB-F301-4D0A-92A9-DCEBB78203AE
        electronic_funds_transfer_form: 10817A22-6DCF-4CAE-B379-AF4B7DF54047
        account_transfer_form:          60E63BD4-6047-448C-B390-D8EC734B94C1
        check_request:                  BBD7E655-E694-4D77-A5AA-833714A2FD7B
        wire_instructions:              19C426B5-ACAB-46B0-9EF6-963DA60CD8CF
        ira_distribution_form:          907D8593-315D-4F67-8224-4B649B8AD4BD
        beneficiary_designation_form:   CC91DE97-A57B-4BED-BD33-5B5F3FDF530F

    wealthbot_docusign.api_client.class: Wealthbot\SignatureBundle\Docusign\DocusignSessionPersistence
    wealthbot_docusign.account_docusign.class: Wealthbot\ClientBundle\Entity\ClientAccountDocusign
    wealthbot_docusign.account_signature.class: Wealthbot\SignatureBundle\Entity\DocumentSignature
    wealthbot_docusign.account_owner_signature.class: Wealthbot\SignatureBundle\Entity\DocumentOwnerSignature

services:
    wealthbot_docusign.account_docusign.manager:
        class: Wealthbot\SignatureBundle\Manager\AccountDocusignManager
        arguments: [@doctrine.orm.entity_manager, %wealthbot_docusign.account_docusign.class%]

    wealthbot_docusign.document_signature.manager:
        class: Wealthbot\SignatureBundle\Manager\DocumentSignatureManager
        arguments: [@doctrine.orm.entity_manager, %wealthbot_docusign.account_signature.class%, %wealthbot_docusign.account_owner_signature.class%]

    wealthbot_docusign.api_client:
        class: %wealthbot_docusign.api_client.class%
        arguments: [%wealthbot_docusign.connection%, @session]

    wealthbot_docusign.electronic_signature_service:
        class: Wealthbot\SignatureBundle\Service\ElectronicSignatureService
        arguments: [@wealthbot_docusign.api_client, @wealthbot_docusign.document_signature.manager, @wealthbot_docusign.account_docusign.manager, %wealthbot_docusign.templates%]

    wealthbot_user.twig.signature_extension:
        class: Wealthbot\SignatureBundle\Twig\SignatureTwigExtension
        arguments: [@wealthbot_docusign.document_signature.manager]
        tags:
            - { name: twig.extension }
